// ============================================================================
// File: tb_neo_gpu_top.cpp
// Description: Verilator Testbench with QEMU Co-simulation Support
//              Tests: Host Doorbell -> GPU Compute -> Interrupt
// ============================================================================
#include <verilated.h>
#include "Vneo_gpu_top.h"           // Generated by Verilator
#include "Vneo_gpu_top__Dpi.h"      // DPI exports/imports
#include "gpu_cosim.h"

#include <iostream>
#include <fstream>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <cstring>
#include <thread>
#include <atomic>

// Simulation control
vluint64_t main_time = 0;           // Current simulation time
Vneo_gpu_top* top;                  // DUT instance
std::atomic<bool> sim_running(true);
std::atomic<bool> irq_pending(false);

// Shared Memory handle
gpu_shm_region_t* shm = nullptr;
int shm_fd = -1;

// PCIe TLP state (internal to testbench)
struct {
    uint64_t bar0_base = 0x10000000;  // Simulated BAR0 address
    uint64_t bar1_base = 0x20000000;  // Simulated VRAM address
    uint32_t pending_irq = 0;
} pcie_state;

// ============================================================================
// Helper Functions
// ============================================================================

void connect_shm() {
    shm_fd = shm_open("/gpu_cosim_shm", O_CREAT | O_RDWR, 0666);
    if (shm_fd < 0) {
        perror("shm_open failed");
        exit(1);
    }
    ftruncate(shm_fd, SHM_SIZE);
    shm = (gpu_shm_region_t*)mmap(NULL, SHM_SIZE, PROT_READ | PROT_WRITE, 
                                   MAP_SHARED, shm_fd, 0);
    memset((void*)shm, 0, SHM_SIZE);
    std::cout << "[Verilator] Shared memory connected" << std::endl;
}

void disconnect_shm() {
    if (shm) munmap((void*)shm, SHM_SIZE);
    if (shm_fd >= 0) close(shm_fd);
    shm_unlink("/gpu_cosim_shm");
}

// ============================================================================
// PCIe TLP Interface (DPI exports called by RTL)
// ============================================================================

// Called by RTL when it wants to send TLP to Host (QEMU)
extern "C" void dpi_pcie_tx_tlp(
    const svBitVecVal* data,    // 32-bit data
    svBit valid,
    svBit is_irq                // If set, this is an interrupt TLP
) {
    if (!valid || !shm) return;
    
    uint32_t tx_data = data[0];
    
    // Write to response queue (RTL -> QEMU)
    uint32_t tail = shm->resp_tail;
    tlp_packet_t* pkt = &shm->resp_queue[tail % SHM_QUEUE_DEPTH];
    
    pkt->magic = GPU_MAGIC_RESP;
    pkt->type = is_irq ? TLP_IRQ_ASSERT : TLP_MEM_READ;  // Simplified
    pkt->data[0] = tx_data;
    pkt->tag = tail;
    
    shm->resp_tail = tail + 1;
    
    if (is_irq) {
        std::cout << "[Verilator] Interrupt sent to QEMU, data=0x" 
                  << std::hex << tx_data << std::dec << std::endl;
        irq_pending = true;
    }
}

// Called by RTL on clock posedge to check for incoming TLPs
extern "C" void dpi_pcie_rx_poll(svBit* valid, svBitVecVal* addr, svBitVecVal* data, 
                                  svBit is_write, svBitVecVal* byte_en) {
    *valid = 0;
    if (!shm) return;
    
    // Check request queue (QEMU -> RTL)
    uint32_t head = shm->req_head;
    if (head == shm->req_tail) return;  // Empty
    
    tlp_packet_t* pkt = &shm->req_queue[head % SHM_QUEUE_DEPTH];
    if (pkt->magic != GPU_MAGIC_REQ) return;
    
    // Parse TLP
    *valid = 1;
    addr[0] = pkt->addr;
    addr[1] = pkt->addr >> 32;
    data[0] = pkt->data[0];
    *reinterpret_cast<svBit*>(is_write) = (pkt->type == TLP_MEM_WRITE) ? 1 : 0;
    byte_en[0] = pkt->byte_enable;
    
    // Advance queue
    shm->req_head = head + 1;
    
    // Log
    std::cout << "[Verilator] Received TLP: type=" << pkt->type 
              << " addr=0x" << std::hex << pkt->addr 
              << " data=0x" << pkt->data[0] << std::dec << std::endl;
}

// ============================================================================
// Simulation Main Loop
// ============================================================================

void simulation_thread() {
    // Initialize Verilator
    Verilated::commandArgs(0, (const char**)nullptr);
    top = new Vneo_gpu_top;
    
    // Reset
    top->rst_n = 0;
    top->clk_sys = 0;
    top->clk_pcie = 0;
    
    // Hold reset for 100ns (10 cycles)
    for (int i = 0; i < 20; i++) {
        top->clk_sys = !top->clk_sys;
        top->eval();
        main_time += 5;
    }
    top->rst_n = 1;
    
    std::cout << "[Verilator] Reset released, simulation starting" << std::endl;
    shm->rtl_ready = 1;
    
    // Main simulation loop
    while (sim_running && !Verilated::gotFinish()) {
        // Clock generation (1GHz sys, 250MHz pcie = 4:1 ratio)
        // 1ns precision: sys period = 1ns, pcie period = 4ns
        
        // Toggle PCIe clock every 2 cycles (4ns period)
        if (main_time % 4 == 0) {
            top->clk_pcie = !top->clk_pcie;
        }
        
        // Toggle Sys clock every cycle (2ns period, actually 500MHz for easier sim)
        top->clk_sys = !top->clk_sys;
        
        top->eval();
        
        // Update SHM cycle count
        shm->rtl_cycles = main_time;
        
        main_time += 1;
        
        // Timeout check
        if (main_time > 1000000) {  // 1ms simulation time
            std::cout << "[Verilator] Timeout, stopping simulation" << std::endl;
            break;
        }
    }
    
    // Cleanup
    top->final();
    delete top;
}

// ============================================================================
// Test Sequence (Host behavior simulation)
// ============================================================================

void host_test_sequence() {
    // Wait for QEMU and RTL ready
    while (!shm->qemu_ready || !shm->rtl_ready) {
        usleep(1000);
    }
    std::cout << "[Test] Both sides ready, starting test sequence" << std::endl;
    
    // Test 1: Write to GPU Control Register (BAR0)
    // This simulates Host driver configuring the GPU
    
    auto send_tlp = [&](tlp_type_t type, uint64_t addr, uint32_t data) {
        uint32_t tail = shm->req_tail;
        tlp_packet_t* pkt = &shm->req_queue[tail % SHM_QUEUE_DEPTH];
        
        pkt->magic = GPU_MAGIC_REQ;
        pkt->type = type;
        pkt->addr = addr;
        pkt->data[0] = data;
        pkt->byte_enable = 0xF;  // 4 bytes
        pkt->length = 4;
        pkt->tag = tail;
        
        shm->req_tail = tail + 1;
        std::cout << "[Test] Sent TLP: type=" << type << " addr=0x" 
                  << std::hex << addr << " data=0x" << data << std::dec << std::endl;
    };
    
    sleep(1);  // Wait for simulation to start
    
    // Step 1: Configure Grid Dimensions (Write BAR0 registers)
    uint64_t bar0 = 0x10000000;  // Simulated BAR0 address
    send_tlp(TLP_MEM_WRITE, bar0 + GPU_REG_GRID_X, 0x00000002);  // Grid X = 2
    send_tlp(TLP_MEM_WRITE, bar0 + GPU_REG_GRID_Y, 0x00000002);  // Grid Y = 2
    send_tlp(TLP_MEM_WRITE, bar0 + GPU_REG_GRID_Z, 0x00000001);  // Grid Z = 1
    
    // Step 2: Write Kernel Code Address
    send_tlp(TLP_MEM_WRITE, bar0 + GPU_REG_KERNEL_ADDR, 0x00001000);
    
    // Step 3: Ring the Doorbell (This triggers GPU computation)
    std::cout << "[Test] Ringing Doorbell..." << std::endl;
    send_tlp(TLP_MEM_WRITE, bar0 + GPU_REG_DOORBELL, 0x00000001);
    
    // Step 4: Wait for Interrupt from GPU
    std::cout << "[Test] Waiting for GPU completion interrupt..." << std::endl;
    int timeout = 100;  // 10 seconds
    while (!irq_pending && timeout-- > 0) {
        sleep(1);
    }
    
    if (irq_pending) {
        std::cout << "[Test] SUCCESS: Interrupt received from GPU!" << std::endl;
        
        // Step 5: Acknowledge Interrupt (Read status register)
        send_tlp(TLP_MEM_READ, bar0 + GPU_REG_IRQ_ACK, 0);
    } else {
        std::cout << "[Test] FAIL: Timeout waiting for interrupt" << std::endl;
    }
    
    // Stop simulation
    sleep(2);
    sim_running = false;
}

// ============================================================================
// Main Entry
// ============================================================================

int main(int argc, char** argv) {
    std::cout << "========================================" << std::endl;
    std::cout << "NeoGPU Verilator + QEMU Co-simulation" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // Setup shared memory
    connect_shm();
    
    // Signal ready
    shm->rtl_ready = 0;
    shm->req_head = 0;
    shm->req_tail = 0;
    shm->resp_head = 0;
    shm->resp_tail = 0;
    
    // Start simulation in separate thread
    std::thread sim_thread(simulation_thread);
    
    // Run test sequence (this would be QEMU in real scenario)
    host_test_sequence();
    
    // Cleanup
    sim_thread.join();
    disconnect_shm();
    
    std::cout << "Simulation complete. Time=" << main_time << " cycles" << std::endl;
    return 0;
}